/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.dao.EspecialidadeDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 22282204
 */
public class EspecialidadesPanel extends javax.swing.JPanel {

    /**
     * Creates new form EspecialidadesPanel
     */
    public EspecialidadesPanel() {
        initComponents();
        EspecialidadeDAO.criarListaDeEspecialidaddes();
        preencherTabela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelListaDeEspecialidades = new javax.swing.JPanel();
        scrollEspecialidades = new javax.swing.JScrollPane();
        tableEspecialidades = new javax.swing.JTable();
        buttonCriarEspecialidade = new javax.swing.JButton();
        buttonEditarEspecialidade = new javax.swing.JButton();
        buttonApagarEspecialidade = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(880, 380));
        setLayout(null);

        panelListaDeEspecialidades.setBackground(new java.awt.Color(51, 51, 51));
        panelListaDeEspecialidades.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista De Especialidades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 204, 51))); // NOI18N
        panelListaDeEspecialidades.setForeground(new java.awt.Color(51, 51, 51));
        panelListaDeEspecialidades.setLayout(null);

        scrollEspecialidades.setForeground(new java.awt.Color(51, 51, 51));

        tableEspecialidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollEspecialidades.setViewportView(tableEspecialidades);

        panelListaDeEspecialidades.add(scrollEspecialidades);
        scrollEspecialidades.setBounds(10, 20, 860, 260);

        buttonCriarEspecialidade.setBackground(new java.awt.Color(0, 204, 153));
        buttonCriarEspecialidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/adicionar-botao.png"))); // NOI18N
        buttonCriarEspecialidade.setToolTipText("Criar Nova Especialidade");
        buttonCriarEspecialidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelListaDeEspecialidades.add(buttonCriarEspecialidade);
        buttonCriarEspecialidade.setBounds(800, 300, 50, 50);

        buttonEditarEspecialidade.setBackground(new java.awt.Color(255, 204, 51));
        buttonEditarEspecialidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/editar.png"))); // NOI18N
        buttonEditarEspecialidade.setToolTipText("Editar Especialidade Selecionada");
        buttonEditarEspecialidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelListaDeEspecialidades.add(buttonEditarEspecialidade);
        buttonEditarEspecialidade.setBounds(720, 300, 50, 50);

        buttonApagarEspecialidade.setBackground(new java.awt.Color(255, 51, 0));
        buttonApagarEspecialidade.setForeground(new java.awt.Color(204, 0, 0));
        buttonApagarEspecialidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/imagens/backspace.png"))); // NOI18N
        buttonApagarEspecialidade.setToolTipText("Apagar Especialidade Selecionada");
        buttonApagarEspecialidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelListaDeEspecialidades.add(buttonApagarEspecialidade);
        buttonApagarEspecialidade.setBounds(640, 300, 50, 50);

        add(panelListaDeEspecialidades);
        panelListaDeEspecialidades.setBounds(0, 0, 880, 380);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonApagarEspecialidade;
    private javax.swing.JButton buttonCriarEspecialidade;
    private javax.swing.JButton buttonEditarEspecialidade;
    private javax.swing.JPanel panelListaDeEspecialidades;
    private javax.swing.JScrollPane scrollEspecialidades;
    private javax.swing.JTable tableEspecialidades;
    // End of variables declaration//GEN-END:variables

    private void preencherTabela() {
   
        tableEspecialidades.setModel(EspecialidadeDAO.getEspecialidadesModel());

    }

}
